### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by xiaoxiangmoe** [chenlupeng007/React-Universal#1]
* 你这里涉及了前后端，为什么不采用 monorepo 的方式呢？ 建议看看 yarn workspace 和 lerna。至于一起启动前后端，我在根下的 package.json 的 script  字段加了句 `"start": "lerna run --parallel start"`。它会调用各个包的 start 脚本。
* redux 不太适合大部分项目，一般的项目使用新出的 hooks 就好了，简单省心
* 不建议写太多的 webpack 配置，自己维护升级还是挺累的。如果想自己维护的话，仿照 create-react-app 这个项目，单独开一个项目，写一个第三方的 react-scripts，配合上文档。
* withStyles 这种 hoc 现在也不常用了，我和我的朋友一般使用 https://next.material-ui.com/css-in-js/basics/#hook-api
* 如果能加上部署脚本就更好了。可以考虑的部署target的有 https://zeit.co/now ， https://www.netlify.com/ ，还有 https://firebase.google.com/ 等。其中 netlify 支持 aws lambda，是一个很便宜的，而且免费额度很高的托管的后端服务。
* 如果还想更进一步就搞一搞 lint， typescript，还有测试

**Comment by chenlupeng007** [comment]
感谢您的建议, 以后会慢慢根据实际需要添加一些功能.
您的建议给我提供了一些很好的方向.

**Comment by chenlupeng007** [comment]
@xiaoxiangmoe 你好! 请问您是魔门塔的前端工程师吗？ 不知道你们组还招不招前端工程师，可否让我去面试一次？

**Comment by xiaoxiangmoe** [comment]
@chenlupeng007 你的QQ或者微信是多少啊，聊天工具里聊吧。

**Comment by chenlupeng007** [comment]
@xiaoxiangmoe wx: chenlp-1314
